AHOY:
	short: AHOY
	color: 1dbf6e
Špilberk:
	short: Špilberk
	color: 1d89bf
Scalní letňák:
	short: Scala
	color: 381dbf
Restaurace Pavillon:
	short: Pavillon
	color: bf1dbf
Městské divadlo:
	short: MdB
	color: bf1d38
Radnice Brna-střed:
	short: Střed
	color: bf891d
Nádvoří staré radnice:
	short: Nádvoří
	color: 6ebf1d
