AHOY:
	short: AHOY
	color: 32AB22
Špilberk:
	short: Špilberk
	color: 227517
Scalní letňák:
	short: Scala
	color: F2C230
Restaurace Pavillon:
	short: Pavillon
	color: 023770
Městské divadlo:
	short: MdB
	color: 0576F2
Radnice Brna-střed:
	short: Střed
	color: F23E2E
Nádvoří staré radnice:
	short: Nádvoří
	color: F28630
