Městské divadlo:
	short: MdB
Radnice Brna-střed:
	short: Střed
Scalní letňák:
	short: Scala
Špilberk:
	short: Špilberk
Restaurace Pavillon:
	short: Pavillon
Nádvoří staré radnice:
	short: Nádvoří
AHOY:
	short: AHOY
